/**
 * Contract access layer for NØVA's Compact contract (contract/src/nova.compact).
 *
 *  - The compiled contract definition ships with the `nova-contract`
 *    workspace (generated by the official Compact compiler).
 *  - READS of the deployed contract's public aggregates go through the
 *    server route /api/ledger/state (indexer GraphQL, decoded via the
 *    generated ledger accessor).
 *  - WRITES (initialize / registerCredential / attest) run the real Compact
 *    witness + proof pipeline through the Midnight.js provider stack — a
 *    server-side flow implemented by scripts/deploy-ledger.ts. The browser
 *    app never fabricates contract data: this module only mirrors circuit
 *    and ledger NAMES (kept test-synced with the generated bindings) and
 *    config validation.
 */

export const NOVA_CIRCUITS = [
  'operatorPublicKey',
  'credentialCommitmentFor',
  'accumulatorNext',
  'attestationFor',
  'initialize',
  'suspend',
  'resume',
  'registerCredential',
  'attest',
] as const;

export const NOVA_LEDGERS = [
  'status',
  'owner',
  'sequence',
  'credentialAccumulator',
  'credentialCount',
  'proofCount',
  'lastAttestation',
  'lastAttestationScope',
] as const;

/** Circuits exposed by the published contract (for docs & developer UI). */
export function contractCircuits(): readonly string[] {
  return NOVA_CIRCUITS;
}

export function contractName(): string {
  return 'Nova';
}

/** Validate the format of a contract id (64-hex) for config screens. */
export function isValidContractId(value: string): boolean {
  return /^[0-9a-f]{64}$/i.test(value);
}
